### ISSUE TITLE
Criar classes Loja e Produtora 

### ISSUE THREAD

**Issue by MarcosBB** [MarcosBB/loja-de-jogos#5]
![image](https://github.com/MarcosBB/locadora-de-jogos/assets/50207805/ee5dea11-e3ec-4d89-98c0-74ff7c89a9e8)

deve-se decidir se faz mais sentido serem **headadas** ou **implementadas** de uma class `Empresa`

**Comment by luizzmariz** [comment]
git fetch origin
git checkout 5-criar-classes-loja-e-produtora
